name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: '[Feature]: '
labels: ['✨ Enhancement']
assignees: []
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: As a user, I want...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to happen?
      placeholder: Describe the feature or behavior
    validations:
      required: true

  - type: textarea
    id: designs
    attributes:
      label: Design / References
      description: Mockups, Figma links, screenshots, or examples
      placeholder: Links or images
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Anything else that helps us understand the request
    validations:
      required: false
