FROM node:22.13-alpine AS builder

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1

RUN npm i -g corepack@latest
RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

COPY . .

RUN pnpm run bublik:build-storybook

FROM nginx:alpine

COPY --from=builder /app/dist/storybook/bublik /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
