FROM node:17.9.0

ENV PNPM_HOME="/root/.local/share/pnpm"
ENV PATH="${PATH}:${PNPM_HOME}"

RUN npm install --global pnpm

RUN pnpm add -g nx

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .

EXPOSE 4200

CMD ["pnpm", "run", "nx", "serve", "--host=0.0.0.0"]
