FROM node:24.11-alpine AS base

ARG PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=${PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD}
ENV BASE_URL="/v2"

RUN npm i -g corepack@latest
RUN corepack enable

COPY . /app
WORKDIR /app

FROM base AS runner

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile --ignore-scripts

EXPOSE 4200

CMD pnpm run nx serve --host=0.0.0.0 --base=${BASE_URL}
