FROM node:20-slim AS base

ARG PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=${PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD}
ENV BASE_URL="/v2"

RUN corepack enable

COPY . /app
WORKDIR /app

FROM base as runner

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install

EXPOSE 4200

CMD ["pnpm", "run", "nx", "serve", "--host=0.0.0.0", "--base=${BASE_URL}"]
